name: Feature request
description: Suggest something for DriftwoodServer
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like it to do
    validations:
      required: true
